CREATE TABLE DS_USER (
  ID            VARCHAR(64)      NOT NULL,
  FIRST_NAME     VARCHAR(32),
  LASTNAME      VARCHAR(32),
  AGE           INT(3),
  ACTIVE        INT(1),
  CREATED_AT    TIMESTAMP,
  CREATOR    VARCHAR(20),
  updated_At    TIMESTAMP,
  updator    VARCHAR(20),
  EMAIL_ADDRESS VARCHAR(128),
  MANAGER_ID    INT(11),
  BINARY_DATA   BLOB,
  DATE_OF_BIRTH DATE,
  country       VARCHAR(64),
  city          VARCHAR(64),
  street_name   VARCHAR(64),
  street_no     VARCHAR(64),
  PRIMARY KEY (ID)
);


CREATE TABLE EMBEDDED_ID_TABLE (
  
   ID1 VARCHAR(50) NOT NULL,
   
   ID2 VARCHAR(50) NOT NULL,

   FIELD1 VARCHAR(100),
   PRIMARY KEY (ID1, ID2)
);